### ISSUE TITLE
中川凰蘭佬

### ISSUE THREAD

**Issue by 753769554** [TCOTC/Whisper#7]
字体外观选项里是否可以增加
改变字体大小的选项
另外
稍稍吐槽下
字体背景颜色是覆盖了字体的一半
看着稍微别扭呐

**Comment by TCOTC** [comment]
### 01

浅吟主题在设计上希望用户更简单地使用思源、不在排版与外观效果上花费精力，所以在外观菜单中隐藏了“字号”与“字体效果”，目前不计划提供配置选项。你可以使用如下 CSS 代码片段重新显示：

```css
.protyle-font > div:has(> .fn__flex > .b3-switch) {
	display: flex;
}
.protyle-font > div:has(> .fn__flex > .b3-slider),
.protyle-font > div.fn__hr--b {
	display: block;
}
```

### 02

半高背景色是主题的风格，以后做配色方案的话会考虑提供选项修改，感谢反馈

- [x] 配置选项要做 i18n：简中、繁中、英语、日语
